# Resources/config/services.yml
services:

    wbw.bootstrap.twig.extension.assets:
        class:  WBW\Bundle\BootstrapBundle\Twig\Extension\AssetsTwigExtension
        public: true
        arguments: [ "@twig" ]
        tags:
            - { name: "twig.extension" }

    wbw.bootstrap.twig.extension.component.alert:
        class:  WBW\Bundle\BootstrapBundle\Twig\Extension\Component\AlertTwigExtension
        public: true
        arguments: [ "@twig" ]
        calls:
            - [ "setVersion", [ "%wbw_bootstrap.version%" ] ]
        tags:
            - { name: "twig.extension" }

    wbw.bootstrap.twig.extension.component.badge:
        class:  WBW\Bundle\BootstrapBundle\Twig\Extension\Component\BadgeTwigExtension
        public: true
        arguments: [ "@twig" ]
        calls:
            - [ "setVersion", [ "%wbw_bootstrap.version%" ] ]
        tags:
            - { name: "twig.extension" }

    wbw.bootstrap.twig.extension.component.breadcrumb:
        class:  WBW\Bundle\BootstrapBundle\Twig\Extension\Component\BreadcrumbTwigExtension
        public: true
        arguments: [ "@twig", "@translator" ]
        tags:
            - { name: "twig.extension" }

    wbw.bootstrap.twig.extension.component.button_group:
        class:  WBW\Bundle\BootstrapBundle\Twig\Extension\Component\ButtonGroupTwigExtension
        public: true
        arguments: [ "@twig" ]
        tags:
            - { name: "twig.extension" }

    wbw.bootstrap.twig.extension.component.dropdown:
        class:  WBW\Bundle\BootstrapBundle\Twig\Extension\Component\DropdownTwigExtension
        public: true
        arguments: [ "@twig" ]
        tags:
            - { name: "twig.extension" }

    wbw.bootstrap.twig.extension.component.glyphicon:
        class:  WBW\Bundle\BootstrapBundle\Twig\Extension\Component\GlyphiconTwigExtension
        public: true
        arguments: [ "@twig" ]
        calls:
            - [ "setVersion", [ "%wbw_bootstrap.version%" ] ]
        tags:
            - { name: "twig.extension" }

    wbw.bootstrap.twig.extension.component.icon:
        class:  WBW\Bundle\BootstrapBundle\Twig\Extension\Component\IconTwigExtension
        public: true
        arguments: [ "@twig" ]
        tags:
            - { name: "twig.extension" }

    wbw.bootstrap.twig.extension.component.label:
        class:  WBW\Bundle\BootstrapBundle\Twig\Extension\Component\LabelTwigExtension
        public: true
        arguments: [ "@twig" ]
        calls:
            - [ "setVersion", [ "%wbw_bootstrap.version%" ] ]
        tags:
            - { name: "twig.extension" }

    wbw.bootstrap.twig.extension.component.nav:
        class:  WBW\Bundle\BootstrapBundle\Twig\Extension\Component\NavTwigExtension
        public: true
        arguments: [ "@twig" ]
        tags:
            - { name: "twig.extension" }

    wbw.bootstrap.twig.extension.component.progress_bar:
        class:  WBW\Bundle\BootstrapBundle\Twig\Extension\Component\ProgressBarTwigExtension
        public: true
        arguments: [ "@twig" ]
        calls:
            - [ "setVersion", [ "%wbw_bootstrap.version%" ] ]
        tags:
            - { name: "twig.extension" }


    wbw.bootstrap.twig.extension.css.button:
        class:  WBW\Bundle\BootstrapBundle\Twig\Extension\CSS\ButtonTwigExtension
        public: true
        arguments: [ "@twig" ]
        calls:
            - [ "setVersion", [ "%wbw_bootstrap.version%" ] ]
        tags:
            - { name: "twig.extension" }

    wbw.bootstrap.twig.extension.css.code:
        class:  WBW\Bundle\BootstrapBundle\Twig\Extension\CSS\CodeTwigExtension
        public: true
        arguments: [ "@twig" ]
        tags:
            - { name: "twig.extension" }

    wbw.bootstrap.twig.extension.css.grid:
        class:  WBW\Bundle\BootstrapBundle\Twig\Extension\CSS\GridTwigExtension
        public: true
        arguments: [ "@twig" ]
        tags:
            - { name: "twig.extension" }

    wbw.bootstrap.twig.extension.css.typography:
        class:  WBW\Bundle\BootstrapBundle\Twig\Extension\CSS\TypographyTwigExtension
        public: true
        arguments: [ "@twig" ]
        tags:
            - { name: "twig.extension" }

    wbw.bootstrap.twig.extension.utility.form_button:
        class:  WBW\Bundle\BootstrapBundle\Twig\Extension\Utility\FormButtonTwigExtension
        public: true
        arguments: [ "@twig", "@translator", "@wbw.bootstrap.twig.extension.css.button" ]
        tags:
            - { name: "twig.extension" }

    wbw.bootstrap.twig.extension.utility.role_label:
        class:  WBW\Bundle\BootstrapBundle\Twig\Extension\Utility\RoleLabelTwigExtension
        public: true
        arguments: [ "@twig", "@translator", "@wbw.bootstrap.twig.extension.component.label" ]
        tags:
            - { name: "twig.extension" }

    wbw.bootstrap.twig.extension.utility.table_button:
        class:  WBW\Bundle\BootstrapBundle\Twig\Extension\Utility\TableButtonTwigExtension
        public: true
        arguments: [ "@twig", "@translator", "@wbw.bootstrap.twig.extension.css.button" ]
        tags:
            - { name: "twig.extension" }
